version: '3'
#WP, mysql, WP CLI install, PHPMYAdmin and memcached
#WP CLI continues to try a core install until it is successful then it exits

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "49000:8080"
    restart: always
    volumes:
      - ./jenkins:/var/jenkins_home
networks:
  wpsite:
